server:
  port: 9200

spring:
  cloud:
    gateway:
      routes:
        #Route Mapping
      - id: cropDetails              #RouteIdentifier
        uri: http://localhost:8087/         #Respective microservice URL which needs to be mapped
         #Request Context Path Mapping
        predicates:
        - Path=/api/cropdetails/**          

        #Route Mapping - With out Filter
      - id: CartManagement
        uri: http://localhost:8088/
        predicates:
        - Path=/api/cart/**

        #Route Mapping - With out Filters 
      - id: OrderManagement
        uri: http://localhost:8089/
        predicates:
        - Path=/api/dealer/**
        
          #Route Mapping - With out Filters 
      - id: UserManagement
        uri: http://localhost:9100/
        predicates:
        - Path=/api/profile/**
 
  application:
    name: Eureka-with-api-gateway